version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - webnet    
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - webnet    
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: viveknathani
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assignexpert
    ports:
      - "5432:5432"
    networks:
      - webnet
networks:
  webnet:  
    
