const code = document.getElementById("code");

let time = 200;

code.classList.remove("borderBlink");
setTimeout(() => code.innerHTML += "<span style='color: black;'>c</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>o</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>n</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>s</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>o</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>l</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>e</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>.</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>l</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>o</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>g</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>(</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "'", time);
time += 170;
setTimeout(() => code.innerHTML += "l", time);
time += 170;
setTimeout(() => code.innerHTML += "o", time);
time += 170;
setTimeout(() => code.innerHTML += "a", time);
time += 170;
setTimeout(() => code.innerHTML += "d", time);
time += 170;
setTimeout(() => code.innerHTML += "i", time);
time += 170;
setTimeout(() => code.innerHTML += "n", time);
time += 170;
setTimeout(() => code.innerHTML += "g", time);
time += 170;
setTimeout(() => code.innerHTML += "'", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>)</span>", time);
time += 170;
setTimeout(() => code.innerHTML += "<span style='color: black;'>;</span>", time);
code.classList.add("borderBlink");
time = 200;


setInterval(writeCode, 5500);

function writeCode() {
   code.classList.remove("borderBlink");
   code.innerHTML = "";
   setTimeout(() => code.innerHTML += "<span style='color: black;'>c</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>o</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>n</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>s</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>o</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>l</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>e</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>.</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>l</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>o</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>g</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>(</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "'", time);
   time += 170;
   setTimeout(() => code.innerHTML += "l", time);
   time += 170;
   setTimeout(() => code.innerHTML += "o", time);
   time += 170;
   setTimeout(() => code.innerHTML += "a", time);
   time += 170;
   setTimeout(() => code.innerHTML += "d", time);
   time += 170;
   setTimeout(() => code.innerHTML += "i", time);
   time += 170;
   setTimeout(() => code.innerHTML += "n", time);
   time += 170;
   setTimeout(() => code.innerHTML += "g", time);
   time += 170;
   setTimeout(() => code.innerHTML += "'", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>)</span>", time);
   time += 170;
   setTimeout(() => code.innerHTML += "<span style='color: black;'>;</span>", time);
   code.classList.add("borderBlink");
   time = 200;
}